### ISSUE TITLE
Make ManageSieve accessible from outside

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-sievefilters#15]
Some email clients have native support for managing ManageSieve filters.
It could be interesting to explore ways of making the service available to them.

Can IMAP authentication be reused, how do these third-party integrations work?

**Comment by tonioo** [comment]
@almereyda If I understand your need properly, all you have to do is to modify dovecot's config (listen address, port, TLS, etc.)
?

**Comment by almereyda** [comment]
I don't know how to secure it.

**Comment by tonioo** [comment]
Managesieve authentication will use the same configuration as the IMAP one so STARTTLS is already available.
